FROM rocker/r2u:24.04

RUN groupadd app && useradd -g app app
WORKDIR /home/app

COPY app/DESCRIPTION .
RUN R -q -e "remotes::install_deps(upgrade='never')"

COPY app .

RUN chown app:app -R /home/app
USER app
EXPOSE 3838
CMD ["R", "-e", "shiny::runApp(host='0.0.0.0', port=3838)"]
